<a href="https://colab.research.google.com/github/Satish1895/6thSem-ML-Lab/blob/main/1BM23CS306_LAB_5_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

iris_df = pd.read_csv('/content/iris (1).csv')

print("First 5 rows of the DataFrame:")
print(iris_df.head())

print("\nDataFrame Information:")
iris_df.info()

First 5 rows of the DataFrame:
   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

DataFrame Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

# 1. Separate features and target variable
X_iris = iris_df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y_iris = iris_df['species']

# 2. Split the data into training and testing sets (80/20 ratio)
X_train_iris, X_test_iris, y_train_iris, y_test_iris = train_test_split(X_iris, y_iris, test_size=0.2, random_state=42)

# 3. Instantiate a KNeighborsClassifier (choosing n_neighbors=5)
knn_iris = KNeighborsClassifier(n_neighbors=5)

# 4. Train the KNN classifier using the training data
knn_iris.fit(X_train_iris, y_train_iris)

print("Iris dataset preparation and KNN model training complete.")
print(f"X_train_iris shape: {X_train_iris.shape}")
print(f"X_test_iris shape: {X_test_iris.shape}")

Iris dataset preparation and KNN model training complete.
X_train_iris shape: (120, 4)
X_test_iris shape: (30, 4)


In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Make predictions on the test set
y_pred_iris = knn_iris.predict(X_test_iris)

# Calculate and display the accuracy score
accuracy = accuracy_score(y_test_iris, y_pred_iris)
print(f"Accuracy Score: {accuracy:.4f}")

# Generate and display the confusion matrix
conf_matrix = confusion_matrix(y_test_iris, y_pred_iris)
print("\nConfusion Matrix:")
print(conf_matrix)

# Generate and display the classification report
class_report = classification_report(y_test_iris, y_pred_iris)
print("\nClassification Report:")
print(class_report)

Accuracy Score: 1.0000

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [ ]:
import pandas as pd

diabetes_df = pd.read_csv('/content/diabetes.csv')

print("First 5 rows of the DataFrame:")
print(diabetes_df.head())

print("\nDataFrame Information:")
diabetes_df.info()

First 5 rows of the DataFrame:
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  

DataFrame Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

# 1. Separate features and target variable
X_diabetes = diabetes_df.drop('Outcome', axis=1)
y_diabetes = diabetes_df['Outcome']

print("Features and target separated.")
print(f"X_diabetes shape: {X_diabetes.shape}")
print(f"y_diabetes shape: {y_diabetes.shape}")

# 2. Split the data into training and testing sets (80/20 ratio)
X_train_diabetes, X_test_diabetes, y_train_diabetes, y_test_diabetes = train_test_split(X_diabetes, y_diabetes, test_size=0.2, random_state=42)

print("\nData split into training and testing sets.")
print(f"X_train_diabetes shape: {X_train_diabetes.shape}")
print(f"X_test_diabetes shape: {X_test_diabetes.shape}")

# 3. Perform feature scaling on the features
scaler = StandardScaler()
X_train_diabetes_scaled = scaler.fit_transform(X_train_diabetes)
X_test_diabetes_scaled = scaler.transform(X_test_diabetes)

print("\nFeatures scaled using StandardScaler.")
print(f"X_train_diabetes_scaled shape: {X_train_diabetes_scaled.shape}")
print(f"X_test_diabetes_scaled shape: {X_test_diabetes_scaled.shape}")

# 4. Instantiate a KNeighborsClassifier (choosing n_neighbors=5)
knn_diabetes = KNeighborsClassifier(n_neighbors=5)

# 5. Train the KNN classifier using the scaled training data
knn_diabetes.fit(X_train_diabetes_scaled, y_train_diabetes)

print("\nKNN model trained on scaled diabetes data.")

Features and target separated.
X_diabetes shape: (768, 8)
y_diabetes shape: (768,)

Data split into training and testing sets.
X_train_diabetes shape: (614, 8)
X_test_diabetes shape: (154, 8)

Features scaled using StandardScaler.
X_train_diabetes_scaled shape: (614, 8)
X_test_diabetes_scaled shape: (154, 8)

KNN model trained on scaled diabetes data.


In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 1. Make predictions on the scaled test set
y_pred_diabetes = knn_diabetes.predict(X_test_diabetes_scaled)

# 2. Calculate and display the accuracy score
accuracy_diabetes = accuracy_score(y_test_diabetes, y_pred_diabetes)
print(f"Diabetes KNN Model Accuracy: {accuracy_diabetes:.4f}")

# 3. Generate and display the confusion matrix
conf_matrix_diabetes = confusion_matrix(y_test_diabetes, y_pred_diabetes)
print("\nDiabetes KNN Model Confusion Matrix:")
print(conf_matrix_diabetes)

# Optional: Generate and display the classification report for more detailed metrics
class_report_diabetes = classification_report(y_test_diabetes, y_pred_diabetes)
print("\nDiabetes KNN Model Classification Report:")
print(class_report_diabetes)

Diabetes KNN Model Accuracy: 0.6948

Diabetes KNN Model Confusion Matrix:
[[79 20]
 [27 28]]

Diabetes KNN Model Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.80      0.77        99
           1       0.58      0.51      0.54        55

    accuracy                           0.69       154
   macro avg       0.66      0.65      0.66       154
weighted avg       0.69      0.69      0.69       154



In [ ]:
import numpy as np

def euclidean_distance(point1, point2):
    # Ensure numpy is used for calculations
    point1 = np.array(point1)
    point2 = np.array(point2)

    # Calculate the squared difference between corresponding elements
    squared_diff = (point1 - point2)**2

    # Sum these squared differences and take the square root
    distance = np.sqrt(np.sum(squared_diff))

    return distance

# Example usage:
point_a = [1, 2, 3]
point_b = [4, 5, 6]

dist = euclidean_distance(point_a, point_b)
print(f"The Euclidean distance between {point_a} and {point_b} is: {dist:.4f}")

point_c = np.array([0, 0])
point_d = np.array([3, 4])
dist2 = euclidean_distance(point_c, point_d)
print(f"The Euclidean distance between {point_c} and {point_d} is: {dist2:.4f}")

The Euclidean distance between [1, 2, 3] and [4, 5, 6] is: 5.1962
The Euclidean distance between [0 0] and [3 4] is: 5.0000


In [ ]:
import numpy as np
from collections import Counter

def get_neighbors(X_train, y_train, test_instance, k):
    distances = []
    for i in range(len(X_train)):
        train_point = X_train.iloc[i] if hasattr(X_train, 'iloc') else X_train[i]
        label = y_train.iloc[i] if hasattr(y_train, 'iloc') else y_train[i]
        dist = euclidean_distance(test_instance, train_point)
        distances.append((dist, label))

    # Sort by distance
    distances.sort(key=lambda x: x[0])

    # Get the k nearest neighbors
    neighbors = distances[:k]
    return neighbors

# Example usage with Iris dataset:
# Assuming X_train_iris and y_train_iris are already defined from previous steps
if 'X_train_iris' in locals() and 'y_train_iris' in locals():
    # Take the first instance from the test set as an example test_instance
    test_instance_iris = X_test_iris.iloc[0]
    k_value = 5

    iris_neighbors = get_neighbors(X_train_iris, y_train_iris, test_instance_iris, k_value)

    print(f"Test instance for Iris: {test_instance_iris.values}")
    print(f"K-nearest neighbors for Iris (k={k_value}):")
    for dist, label in iris_neighbors:
        print(f"  Distance: {dist:.4f}, Label: {label}")
else:
    print("X_train_iris or y_train_iris not found. Please ensure previous steps are executed.")

Test instance for Iris: [6.1 2.8 4.7 1.2]
K-nearest neighbors for Iris (k=5):
  Distance: 0.2236, Label: versicolor
  Distance: 0.3000, Label: versicolor
  Distance: 0.4359, Label: versicolor
  Distance: 0.5099, Label: versicolor
  Distance: 0.5099, Label: versicolor


In [ ]:
import numpy as np
from collections import Counter

def predict_classification(neighbors):

    # Extract only the labels from the neighbors list
    labels = [label for dist, label in neighbors]

    # Use Counter to find the most common label
    # most_common(1) returns a list of tuples like [('label', count)]
    most_common_labels = Counter(labels).most_common(1)

    # Return the label from the most common item
    return most_common_labels[0][0]

# Example usage with Iris dataset:
# Assuming iris_neighbors is already defined from the previous step
if 'iris_neighbors' in locals():
    predicted_label_iris = predict_classification(iris_neighbors)
    print(f"Predicted label for the Iris test instance: {predicted_label_iris}")
else:
    print("iris_neighbors not found. Please ensure previous steps are executed.")

Predicted label for the Iris test instance: versicolor


In [ ]:
import numpy as np
from collections import Counter
import pandas as pd # Import pandas to handle DataFrame/Series types in X_train, y_train if needed

# Helper function to calculate Euclidean distance
def euclidean_distance(point1, point2):
    return np.sqrt(np.sum((np.array(point1) - np.array(point2))**2))

# Helper function to find k-nearest neighbors
def get_neighbors(X_train, y_train, test_instance, k):
    distances = []
    for i in range(len(X_train)):
        # Handle both DataFrame/Series and numpy array inputs
        train_point = X_train.iloc[i] if isinstance(X_train, pd.DataFrame) else X_train[i]
        label = y_train.iloc[i] if isinstance(y_train, pd.Series) else y_train[i]
        dist = euclidean_distance(test_instance, train_point)
        distances.append((dist, label))

    distances.sort(key=lambda x: x[0])
    neighbors = distances[:k]
    return neighbors

# Helper function to predict classification based on neighbors
def predict_classification(neighbors):
    labels = [label for dist, label in neighbors]
    most_common_labels = Counter(labels).most_common(1)
    return most_common_labels[0][0]

class KNNClassifier:
    def __init__(self, k=5):
        self.k = k
        self.X_train = None
        self.y_train = None
        print(f"KNNClassifier initialized with k={self.k}")

    def fit(self, X, y):
        self.X_train = X
        self.y_train = y
        print("KNNClassifier fit method called. Training data stored.")

    def predict(self, X_test):
        predictions = []
        print(f"Making predictions for {len(X_test)} test instances...")
        for i in range(len(X_test)):
            test_instance = X_test.iloc[i] if isinstance(X_test, pd.DataFrame) else X_test[i]

            # Get k-nearest neighbors
            neighbors = get_neighbors(self.X_train, self.y_train, test_instance, self.k)

            # Predict label based on neighbors
            predicted_label = predict_classification(neighbors)
            predictions.append(predicted_label)
        print("Predictions complete.")
        return np.array(predictions)

print("Custom KNNClassifier class defined.")

# Example usage with Iris dataset (optional, for verification):
if 'X_train_iris' in locals() and 'y_train_iris' in locals() and 'X_test_iris' in locals():
    custom_knn = KNNClassifier(k=5)
    custom_knn.fit(X_train_iris, y_train_iris)
    y_pred_custom_iris = custom_knn.predict(X_test_iris)

    from sklearn.metrics import accuracy_score
    custom_accuracy = accuracy_score(y_test_iris, y_pred_custom_iris)
    print(f"\nCustom KNN Iris Accuracy: {custom_accuracy:.4f}")
else:
    print("\nSkipping Iris example: X_train_iris, y_train_iris, or X_test_iris not found.")


Custom KNNClassifier class defined.
KNNClassifier initialized with k=5
KNNClassifier fit method called. Training data stored.
Making predictions for 30 test instances...
Predictions complete.

Custom KNN Iris Accuracy: 1.0000


In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 1. Initialize an instance of your custom KNNClassifier with k=5
custom_knn_iris = KNNClassifier(k=5)

# 2. Train the custom KNN model using the training data
custom_knn_iris.fit(X_train_iris, y_train_iris)

# 3. Make predictions on the test set
y_pred_custom_iris = custom_knn_iris.predict(X_test_iris)

# 4. Calculate and print the accuracy score
custom_accuracy_iris = accuracy_score(y_test_iris, y_pred_custom_iris)
print(f"\nCustom KNN Iris Model Accuracy: {custom_accuracy_iris:.4f}")

# 5. Generate and print the confusion matrix
custom_conf_matrix_iris = confusion_matrix(y_test_iris, y_pred_custom_iris)
print("\nCustom KNN Iris Model Confusion Matrix:")
print(custom_conf_matrix_iris)

# 6. Generate and print the classification report
custom_class_report_iris = classification_report(y_test_iris, y_pred_custom_iris)
print("\nCustom KNN Iris Model Classification Report:")
print(custom_class_report_iris)

KNNClassifier initialized with k=5
KNNClassifier fit method called. Training data stored.
Making predictions for 30 test instances...
Predictions complete.

Custom KNN Iris Model Accuracy: 1.0000

Custom KNN Iris Model Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Custom KNN Iris Model Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 1. Initialize an instance of your custom KNNClassifier with k=5 for the Diabetes dataset
custom_knn_diabetes = KNNClassifier(k=5)

# 2. Train the custom KNN model using the scaled training data
custom_knn_diabetes.fit(X_train_diabetes_scaled, y_train_diabetes)

# 3. Make predictions on the scaled test set
y_pred_custom_diabetes = custom_knn_diabetes.predict(X_test_diabetes_scaled)

# 4. Calculate and print the accuracy score
custom_accuracy_diabetes = accuracy_score(y_test_diabetes, y_pred_custom_diabetes)
print(f"\nCustom KNN Diabetes Model Accuracy: {custom_accuracy_diabetes:.4f}")

# 5. Generate and print the confusion matrix
custom_conf_matrix_diabetes = confusion_matrix(y_test_diabetes, y_pred_custom_diabetes)
print("\nCustom KNN Diabetes Model Confusion Matrix:")
print(custom_conf_matrix_diabetes)

# 6. Generate and print the classification report
custom_class_report_diabetes = classification_report(y_test_diabetes, y_pred_custom_diabetes)
print("\nCustom KNN Diabetes Model Classification Report:")
print(custom_class_report_diabetes)

KNNClassifier initialized with k=5
KNNClassifier fit method called. Training data stored.
Making predictions for 154 test instances...
Predictions complete.

Custom KNN Diabetes Model Accuracy: 0.6948

Custom KNN Diabetes Model Confusion Matrix:
[[79 20]
 [27 28]]

Custom KNN Diabetes Model Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.80      0.77        99
           1       0.58      0.51      0.54        55

    accuracy                           0.69       154
   macro avg       0.66      0.65      0.66       154
weighted avg       0.69      0.69      0.69       154

